# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'XSFramework' do
    
  use_frameworks!

pod 'YTKNetwork'
pod 'Masonry'
pod 'YYModel'
pod 'XSAdditions'
pod 'MJRefresh'
pod 'SDWebImage'

  target 'XSFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XSFrameworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
