# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'XSFramework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for XSFramework
pod 'AFNetworking'
pod 'Masonry'
pod 'YYModel'
pod 'XSAdditions'
pod 'MJRefresh'

  target 'XSFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XSFrameworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
